### PR TITLE
GP-5529 Add custom fields to activity report

### PR DESCRIPTION
**Pull request by pfigel**
This (magically) adds all activity custom fields as columns/filters in the fastactivity report.

### CODE REVIEW

**Comment by bjendres** [comment]
Sounds great, thank you. 

@pfigel If you're very sure it doesn't break anything, I'll put it in ``1.2``, what do you think?

**Comment by pfigel** [comment]
@bjendres We deployed this today, so if you want to be absolutely sure, we can give our users a day or two to try and break it. 😁

**Comment by pfigel** [comment]
@bjendres no issues reported so far, should be merge-ready.

**Comment by bjendres** [comment]
Thanks, @pfigel

**Pull request merged**
